# Generated by Django 2.2.3 on 2019-07-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0002_auto_20190705_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('toppings', models.ManyToManyField(to='aggregation.Topping')),
            ],
        ),
    ]
