# Generated by Django 2.2.3 on 2019-07-09 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aggregation', '0003_pizza_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championed_by', to='aggregation.Pizza')),
                ('pizzas', models.ManyToManyField(related_name='restaurants', to='aggregation.Pizza')),
            ],
        ),
    ]
